In [1]:
import base64
import pandas as pd
from IPython.display import HTML

In [2]:
import requests
import json
import urllib
import csv

In [3]:
from pandas.io.json import json_normalize

In [4]:
from urllib.request import urlopen
from pprint import pprint

In [5]:
url='http://api.worldbank.org/v2/country?format=json'
coun = urllib.request.urlopen(url)

In [6]:
counT=coun.read()

In [7]:
pprint(counT)

(b'[{"page":1,"pages":6,"per_page":"50","total":299},[{"id":"ABW","iso2Code":"A'
 b'W","name":"Aruba","region":{"id":"LCN","iso2code":"ZJ","value":"Latin Americ'
 b'a & Caribbean "},"adminregion":{"id":"","iso2code":"","value":""},"incomeLev'
 b'el":{"id":"HIC","iso2code":"XD","value":"High income"},"lendingType":{"id":"'
 b'LNX","iso2code":"XX","value":"Not classified"},"capitalCity":"Oranjestad","l'
 b'ongitude":"-70.0167","latitude":"12.5167"},{"id":"AFE","iso2Code":"ZH","name'
 b'":"Africa Eastern and Southern","region":{"id":"NA","iso2code":"NA","value":'
 b'"Aggregates"},"adminregion":{"id":"","iso2code":"","value":""},"incomeLevel"'
 b':{"id":"NA","iso2code":"NA","value":"Aggregates"},"lendingType":{"id":"","is'
 b'o2code":"","value":"Aggregates"},"capitalCity":"","longitude":"","latitude":'
 b'""},{"id":"AFG","iso2Code":"AF","name":"Afghanistan","region":{"id":"SAS","i'
 b'so2code":"8S","value":"South Asia"},"adminregion":{"id":"SAS","iso2code":"8S'
 b'","value":"South Asia"},"incomeLevel":{"id":"LIC","iso2code":"XM","value":"L'
 b'ow income"},"lendingType":{"id":"IDX","iso2code":"XI","value":"IDA"},"capita'
 b'lCity":"Kabul","longitude":"69.1761","latitude":"34.5228"},{"id":"AFR","iso2'
 b'Code":"A9","name":"Africa","region":{"id":"NA","iso2code":"NA","value":"Aggr'
 b'egates"},"adminregion":{"id":"","iso2code":"","value":""},"incomeLevel":{"id'
 b'":"NA","iso2code":"NA","value":"Aggregates"},"lendingType":{"id":"","iso2cod'
 b'e":"","value":"Aggregates"},"capitalCity":"","longitude":"","latitude":""},{'
 b'"id":"AFW","iso2Code":"ZI","name":"Africa Western and Central","region":{"id'
 b'":"NA","iso2code":"NA","value":"Aggregates"},"adminregion":{"id":"","iso2cod'
 b'e":"","value":""},"incomeLevel":{"id":"NA","iso2code":"NA","value":"Aggregat'
 b'es"},"lendingType":{"id":"","iso2code":"","value":"Aggregates"},"capitalCity'
 b'":"","longitude":"","latitude":""},{"id":"AGO","iso2Code":"AO","name":"Angol'
 b'a","region":{"id":"SSF","iso2code":"ZG","value":"Sub-Saharan Africa "},"admi'
 b'nregion":{"id":"SSA","iso2code":"ZF","value":"Sub-Saharan Africa (excluding '
 b'high income)"},"incomeLevel":{"id":"LMC","iso2code":"XN","value":"Lower midd'
 b'le income"},"lendingType":{"id":"IBD","iso2code":"XF","value":"IBRD"},"capit'
 b'alCity":"Luanda","longitude":"13.242","latitude":"-8.81155"},{"id":"ALB","is'
 b'o2Code":"AL","name":"Albania","region":{"id":"ECS","iso2code":"Z7","value":"'
 b'Europe & Central Asia"},"adminregion":{"id":"ECA","iso2code":"7E","value":"E'
 b'urope & Central Asia (excluding high income)"},"incomeLevel":{"id":"UMC","is'
 b'o2code":"XT","value":"Upper middle income"},"lendingType":{"id":"IBD","iso2c'
 b'ode":"XF","value":"IBRD"},"capitalCity":"Tirane","longitude":"19.8172","lati'
 b'tude":"41.3317"},{"id":"AND","iso2Code":"AD","name":"Andorra","region":{"id"'
 b':"ECS","iso2code":"Z7","value":"Europe & Central Asia"},"adminregion":{"id":'
 b'"","iso2code":"","value":""},"incomeLevel":{"id":"HIC","iso2code":"XD","valu'
 b'e":"High income"},"lendingType":{"id":"LNX","iso2code":"XX","value":"Not cla'
 b'ssified"},"capitalCity":"Andorra la Vella","longitude":"1.5218","latitude":"'
 b'42.5075"},{"id":"ARB","iso2Code":"1A","name":"Arab World","region":{"id":"NA'
 b'","iso2code":"NA","value":"Aggregates"},"adminregion":{"id":"","iso2code":""'
 b',"value":""},"incomeLevel":{"id":"NA","iso2code":"NA","value":"Aggregates"},'
 b'"lendingType":{"id":"","iso2code":"","value":"Aggregates"},"capitalCity":"",'
 b'"longitude":"","latitude":""},{"id":"ARE","iso2Code":"AE","name":"United Ara'
 b'b Emirates","region":{"id":"MEA","iso2code":"ZQ","value":"Middle East & Nort'
 b'h Africa"},"adminregion":{"id":"","iso2code":"","value":""},"incomeLevel":{"'
 b'id":"HIC","iso2code":"XD","value":"High income"},"lendingType":{"id":"LNX","'
 b'iso2code":"XX","value":"Not classified"},"capitalCity":"Abu Dhabi","longitud'
 b'e":"54.3705","latitude":"24.4764"},{"id":"ARG","iso2Code":"AR","name":"Argen'
 b'tina","region":{"id":"LCN","iso2code":"ZJ","value":"Latin America & Caribbea'
 b'n "},"adminregion":{"id":"LAC","iso2code":"XJ","value":"Latin America & Cari'
 b'bbean (excluding high income)"},"incomeLevel":{"id":"UMC","iso2code":"XT","v'
 b'alue":"Upper middle income"},"lendingType":{"id":"IBD","iso2code":"XF","valu'
 b'e":"IBRD"},"capitalCity":"Buenos Aires","longitude":"-58.4173","latitude":"-'
 b'34.6118"},{"id":"ARM","iso2Code":"AM","name":"Armenia","region":{"id":"ECS",'
 b'"iso2code":"Z7","value":"Europe & Central Asia"},"adminregion":{"id":"ECA","'
 b'iso2code":"7E","value":"Europe & Central Asia (excluding high income)"},"inc'
 b'omeLevel":{"id":"UMC","iso2code":"XT","value":"Upper middle income"},"lendin'
 b'gType":{"id":"IBD","iso2code":"XF","value":"IBRD"},"capitalCity":"Yerevan","'
 b'longitude":"44.509","latitude":"40.1596"},{"id":"ASM","iso2Code":"AS","name"'
 b':"American Samoa","region":{"id":"EAS","iso2code":"Z4","value":"East Asia & '
 b'Pacific"},"adminregion":{"id":"EAP","iso2code":"4E","value":"East Asia & Pac'
 b'ific (excluding high income)"},"incomeLevel":{"id":"UMC","iso2code":"XT","va'
 b'lue":"Upper middle income"},"lendingType":{"id":"LNX","iso2code":"XX","value'
 b'":"Not classified"},"capitalCity":"Pago Pago","longitude":"-170.691","latitu'
 b'de":"-14.2846"},{"id":"ATG","iso2Code":"AG","name":"Antigua and Barbuda","re'
 b'gion":{"id":"LCN","iso2code":"ZJ","value":"Latin America & Caribbean "},"adm'
 b'inregion":{"id":"","iso2code":"","value":""},"incomeLevel":{"id":"HIC","iso2'
 b'code":"XD","value":"High income"},"lendingType":{"id":"IBD","iso2code":"XF",'
 b'"value":"IBRD"},"capitalCity":"Saint John\'s","longitude":"-61.8456","lat'
 b'itude":"17.1175"},{"id":"AUS","iso2Code":"AU","name":"Australia","region":{"'
 b'id":"EAS","iso2code":"Z4","value":"East Asia & Pacific"},"adminregion":{"id"'
 b':"","iso2code":"","value":""},"incomeLevel":{"id":"HIC","iso2code":"XD","val'
 b'ue":"High income"},"lendingType":{"id":"LNX","iso2code":"XX","value":"Not cl'
 b'assified"},"capitalCity":"Canberra","longitude":"149.129","latitude":"-35.28'
 b'2"},{"id":"AUT","iso2Code":"AT","name":"Austria","region":{"id":"ECS","iso2c'
 b'ode":"Z7","value":"Europe & Central Asia"},"adminregion":{"id":"","iso2code"'
 b':"","value":""},"incomeLevel":{"id":"HIC","iso2code":"XD","value":"High inco'
 b'me"},"lendingType":{"id":"LNX","iso2code":"XX","value":"Not classified"},"ca'
 b'pitalCity":"Vienna","longitude":"16.3798","latitude":"48.2201"},{"id":"AZE",'
 b'"iso2Code":"AZ","name":"Azerbaijan","region":{"id":"ECS","iso2code":"Z7","va'
 b'lue":"Europe & Central Asia"},"adminregion":{"id":"ECA","iso2code":"7E","val'
 b'ue":"Europe & Central Asia (excluding high income)"},"incomeLevel":{"id":"UM'
 b'C","iso2code":"XT","value":"Upper middle income"},"lendingType":{"id":"IBD",'
 b'"iso2code":"XF","value":"IBRD"},"capitalCity":"Baku","longitude":"49.8932","'
 b'latitude":"40.3834"},{"id":"BDI","iso2Code":"BI","name":"Burundi","region":{'
 b'"id":"SSF","iso2code":"ZG","value":"Sub-Saharan Africa "},"adminregion":{"id'
 b'":"SSA","iso2code":"ZF","value":"Sub-Saharan Africa (excluding high income)"'
 b'},"incomeLevel":{"id":"LIC","iso2code":"XM","value":"Low income"},"lendingTy'
 b'pe":{"id":"IDX","iso2code":"XI","value":"IDA"},"capitalCity":"Bujumbura","lo'
 b'ngitude":"29.3639","latitude":"-3.3784"},{"id":"BEA","iso2Code":"B4","name":'
 b'"East Asia & Pacific (IBRD-only countries)","region":{"id":"NA","iso2code":"'
 b'NA","value":"Aggregates"},"adminregion":{"id":"","iso2code":"","value":""},"'
 b'incomeLevel":{"id":"NA","iso2code":"NA","value":"Aggregates"},"lendingType":'
 b'{"id":"","iso2code":"","value":"Aggregates"},"capitalCity":"","longitude":""'
 b',"latitude":""},{"id":"BEC","iso2Code":"B7","name":"Europe & Central Asia (I'
 b'BRD-only countries)","region":{"id":"NA","iso2code":"NA","value":"Aggregates'
 b'"},"adminregion":{"id":"","iso2code":"","value":""},"incomeLevel":{"id":"NA"'
 b',"iso2code":"NA","value":"Aggregates"},"lendingType":{"id":"","iso2code":"",'
 b'"value":"Aggregates"},"capitalCity":"","longitude":"","latitude":""},{"id":"'
 b'BEL","iso2Code":"BE","name":"Belgium","region":{"id":"ECS","iso2code":"Z7","'
 b'value":"Europe & Central Asia"},"adminregion":{"id":"","iso2code":"","value"'
 b':""},"incomeLevel":{"id":"HIC","iso2code":"XD","value":"High income"},"lendi'
 b'ngType":{"id":"LNX","iso2code":"XX","value":"Not classified"},"capitalCity":'
 b'"Brussels","longitude":"4.36761","latitude":"50.8371"},{"id":"BEN","iso2Code'
 b'":"BJ","name":"Benin","region":{"id":"SSF","iso2code":"ZG","value":"Sub-Saha'
 b'ran Africa "},"adminregion":{"id":"SSA","iso2code":"ZF","value":"Sub-Saharan'
 b' Africa (excluding high income)"},"incomeLevel":{"id":"LMC","iso2code":"XN",'
 b'"value":"Lower middle income"},"lendingType":{"id":"IDX","iso2code":"XI","va'
 b'lue":"IDA"},"capitalCity":"Porto-Novo","longitude":"2.6323","latitude":"6.47'
 b'79"},{"id":"BFA","iso2Code":"BF","name":"Burkina Faso","region":{"id":"SSF",'
 b'"iso2code":"ZG","value":"Sub-Saharan Africa "},"adminregion":{"id":"SSA","is'
 b'o2code":"ZF","value":"Sub-Saharan Africa (excluding high income)"},"incomeLe'
 b'vel":{"id":"LIC","iso2code":"XM","value":"Low income"},"lendingType":{"id":"'
 b'IDX","iso2code":"XI","value":"IDA"},"capitalCity":"Ouagadougou","longitude":'
 b'"-1.53395","latitude":"12.3605"},{"id":"BGD","iso2Code":"BD","name":"Banglad'
 b'esh","region":{"id":"SAS","iso2code":"8S","value":"South Asia"},"adminregion'
 b'":{"id":"SAS","iso2code":"8S","value":"South Asia"},"incomeLevel":{"id":"LMC'
 b'","iso2code":"XN","value":"Lower middle income"},"lendingType":{"id":"IDX","'
 b'iso2code":"XI","value":"IDA"},"capitalCity":"Dhaka","longitude":"90.4113","l'
 b'atitude":"23.7055"},{"id":"BGR","iso2Code":"BG","name":"Bulgaria","region":{'
 b'"id":"ECS","iso2code":"Z7","value":"Europe & Central Asia"},"adminregion":{"'
 b'id":"ECA","iso2code":"7E","value":"Europe & Central Asia (excluding high inc'
 b'ome)"},"incomeLevel":{"id":"UMC","iso2code":"XT","value":"Upper middle incom'
 b'e"},"lendingType":{"id":"IBD","iso2code":"XF","value":"IBRD"},"capitalCity":'
 b'"Sofia","longitude":"23.3238","latitude":"42.7105"},{"id":"BHI","iso2Code":"'
 b'B1","name":"IBRD countries classified as high income","region":{"id":"NA","i'
 b'so2code":"NA","value":"Aggregates"},"adminregion":{"id":"","iso2code":"","va'
 b'lue":""},"incomeLevel":{"id":"NA","iso2code":"NA","value":"Aggregates"},"len'
 b'dingType":{"id":"","iso2code":"","value":"Aggregates"},"capitalCity":"","lon'
 b'gitude":"","latitude":""},{"id":"BHR","iso2Code":"BH","name":"Bahrain","regi'
 b'on":{"id":"MEA","iso2code":"ZQ","value":"Middle East & North Africa"},"admin'
 b'region":{"id":"","iso2code":"","value":""},"incomeLevel":{"id":"HIC","iso2co'
 b'de":"XD","value":"High income"},"lendingType":{"id":"LNX","iso2code":"XX","v'
 b'alue":"Not classified"},"capitalCity":"Manama","longitude":"50.5354","latitu'
 b'de":"26.1921"},{"id":"BHS","iso2Code":"BS","name":"Bahamas, The","region":{"'
 b'id":"LCN","iso2code":"ZJ","value":"Latin America & Caribbean "},"adminregion'
 b'":{"id":"","iso2code":"","value":""},"incomeLevel":{"id":"HIC","iso2code":"X'
 b'D","value":"High income"},"lendingType":{"id":"LNX","iso2code":"XX","value":'
 b'"Not classified"},"capitalCity":"Nassau","longitude":"-77.339","latitude":"2'
 b'5.0661"},{"id":"BIH","iso2Code":"BA","name":"Bosnia and Herzegovina","region'
 b'":{"id":"ECS","iso2code":"Z7","value":"Europe & Central Asia"},"adminregion"'
 b':{"id":"ECA","iso2code":"7E","value":"Europe & Central Asia (excluding high '
 b'income)"},"incomeLevel":{"id":"UMC","iso2code":"XT","value":"Upper middle in'
 b'come"},"lendingType":{"id":"IBD","iso2code":"XF","value":"IBRD"},"capitalCit'
 b'y":"Sarajevo","longitude":"18.4214","latitude":"43.8607"},{"id":"BLA","iso2C'
 b'ode":"B2","name":"Latin America & the Caribbean (IBRD-only countries)","regi'
 b'on":{"id":"NA","iso2code":"NA","value":"Aggregates"},"adminregion":{"id":"",'
 b'"iso2code":"","value":""},"incomeLevel":{"id":"NA","iso2code":"NA","value":"'
 b'Aggregates"},"lendingType":{"id":"","iso2code":"","value":"Aggregates"},"cap'
 b'italCity":"","longitude":"","latitude":""},{"id":"BLR","iso2Code":"BY","name'
 b'":"Belarus","region":{"id":"ECS","iso2code":"Z7","value":"Europe & Central A'
 b'sia"},"adminregion":{"id":"ECA","iso2code":"7E","value":"Europe & Central As'
 b'ia (excluding high income)"},"incomeLevel":{"id":"UMC","iso2code":"XT","valu'
 b'e":"Upper middle income"},"lendingType":{"id":"IBD","iso2code":"XF","value":'
 b'"IBRD"},"capitalCity":"Minsk","longitude":"27.5766","latitude":"53.9678"},{"'
 b'id":"BLZ","iso2Code":"BZ","name":"Belize","region":{"id":"LCN","iso2code":"Z'
 b'J","value":"Latin America & Caribbean "},"adminregion":{"id":"LAC","iso2code'
 b'":"XJ","value":"Latin America & Caribbean (excluding high income)"},"incomeL'
 b'evel":{"id":"LMC","iso2code":"XN","value":"Lower middle income"},"lendingTyp'
 b'e":{"id":"IBD","iso2code":"XF","value":"IBRD"},"capitalCity":"Belmopan","lon'
 b'gitude":"-88.7713","latitude":"17.2534"},{"id":"BMN","iso2Code":"B3","name":'
 b'"Middle East & North Africa (IBRD-only countries)","region":{"id":"NA","iso2'
 b'code":"NA","value":"Aggregates"},"adminregion":{"id":"","iso2code":"","value'
 b'":""},"incomeLevel":{"id":"NA","iso2code":"NA","value":"Aggregates"},"lendin'
 b'gType":{"id":"","iso2code":"","value":"Aggregates"},"capitalCity":"","longit'
 b'ude":"","latitude":""},{"id":"BMU","iso2Code":"BM","name":"Bermuda","region"'
 b':{"id":"NAC","iso2code":"XU","value":"North America"},"adminregion":{"id":""'
 b',"iso2code":"","value":""},"incomeLevel":{"id":"HIC","iso2code":"XD","value"'
 b':"High income"},"lendingType":{"id":"LNX","iso2code":"XX","value":"Not class'
 b'ified"},"capitalCity":"Hamilton","longitude":"-64.706","latitude":"32.3293"}'
 b',{"id":"BOL","iso2Code":"BO","name":"Bolivia","region":{"id":"LCN","iso2code'
 b'":"ZJ","value":"Latin America & Caribbean "},"adminregion":{"id":"LAC","iso2'
 b'code":"XJ","value":"Latin America & Caribbean (excluding high income)"},"inc'
 b'omeLevel":{"id":"LMC","iso2code":"XN","value":"Lower middle income"},"lendin'
 b'gType":{"id":"IBD","iso2code":"XF","value":"IBRD"},"capitalCity":"La Paz","l'
 b'ongitude":"-66.1936","latitude":"-13.9908"},{"id":"BRA","iso2Code":"BR","nam'
 b'e":"Brazil","region":{"id":"LCN","iso2code":"ZJ","value":"Latin America & Ca'
 b'ribbean "},"adminregion":{"id":"LAC","iso2code":"XJ","value":"Latin America '
 b'& Caribbean (excluding high income)"},"incomeLevel":{"id":"UMC","iso2code":"'
 b'XT","value":"Upper middle income"},"lendingType":{"id":"IBD","iso2code":"XF"'
 b',"value":"IBRD"},"capitalCity":"Brasilia","longitude":"-47.9292","latitude":'
 b'"-15.7801"},{"id":"BRB","iso2Code":"BB","name":"Barbados","region":{"id":"LC'
 b'N","iso2code":"ZJ","value":"Latin America & Caribbean "},"adminregion":{"id"'
 b':"","iso2code":"","value":""},"incomeLevel":{"id":"HIC","iso2code":"XD","val'
 b'ue":"High income"},"lendingType":{"id":"LNX","iso2code":"XX","value":"Not cl'
 b'assified"},"capitalCity":"Bridgetown","longitude":"-59.6105","latitude":"13.'
 b'0935"},{"id":"BRN","iso2Code":"BN","name":"Brunei Darussalam","region":{"id"'
 b':"EAS","iso2code":"Z4","value":"East Asia & Pacific"},"adminregion":{"id":""'
 b',"iso2code":"","value":""},"incomeLevel":{"id":"HIC","iso2code":"XD","value"'
 b':"High income"},"lendingType":{"id":"LNX","iso2code":"XX","value":"Not class'
 b'ified"},"capitalCity":"Bandar Seri Begawan","longitude":"114.946","latitude"'
 b':"4.94199"},{"id":"BSS","iso2Code":"B6","name":"Sub-Saharan Africa (IBRD-onl'
 b'y countries)","region":{"id":"NA","iso2code":"NA","value":"Aggregates"},"adm'
 b'inregion":{"id":"","iso2code":"","value":""},"incomeLevel":{"id":"NA","iso2c'
 b'ode":"NA","value":"Aggregates"},"lendingType":{"id":"","iso2code":"","value"'
 b':"Aggregates"},"capitalCity":"","longitude":"","latitude":""},{"id":"BTN","i'
 b'so2Code":"BT","name":"Bhutan","region":{"id":"SAS","iso2code":"8S","value":"'
 b'South Asia"},"adminregion":{"id":"SAS","iso2code":"8S","value":"South Asia"}'
 b',"incomeLevel":{"id":"LMC","iso2code":"XN","value":"Lower middle income"},"l'
 b'endingType":{"id":"IDX","iso2code":"XI","value":"IDA"},"capitalCity":"Thimph'
 b'u","longitude":"89.6177","latitude":"27.5768"},{"id":"BWA","iso2Code":"BW","'
 b'name":"Botswana","region":{"id":"SSF","iso2code":"ZG","value":"Sub-Saharan A'
 b'frica "},"adminregion":{"id":"SSA","iso2code":"ZF","value":"Sub-Saharan Afri'
 b'ca (excluding high income)"},"incomeLevel":{"id":"UMC","iso2code":"XT","valu'
 b'e":"Upper middle income"},"lendingType":{"id":"IBD","iso2code":"XF","value":'
 b'"IBRD"},"capitalCity":"Gaborone","longitude":"25.9201","latitude":"-24.6544"'
 b'},{"id":"CAA","iso2Code":"C9","name":"Sub-Saharan Africa (IFC classification'
 b')","region":{"id":"NA","iso2code":"NA","value":"Aggregates"},"adminregion":{'
 b'"id":"","iso2code":"","value":""},"incomeLevel":{"id":"NA","iso2code":"NA","'
 b'value":"Aggregates"},"lendingType":{"id":"","iso2code":"","value":"Aggregate'
 b's"},"capitalCity":"","longitude":"","latitude":""},{"id":"CAF","iso2Code":"C'
 b'F","name":"Central African Republic","region":{"id":"SSF","iso2code":"ZG","v'
 b'alue":"Sub-Saharan Africa "},"adminregion":{"id":"SSA","iso2code":"ZF","valu'
 b'e":"Sub-Saharan Africa (excluding high income)"},"incomeLevel":{"id":"LIC","'
 b'iso2code":"XM","value":"Low income"},"lendingType":{"id":"IDX","iso2code":"X'
 b'I","value":"IDA"},"capitalCity":"Bangui","longitude":"21.6407","latitude":"5'
 b'.63056"},{"id":"CAN","iso2Code":"CA","name":"Canada","region":{"id":"NAC","i'
 b'so2code":"XU","value":"North America"},"adminregion":{"id":"","iso2code":"",'
 b'"value":""},"incomeLevel":{"id":"HIC","iso2code":"XD","value":"High income"}'
 b',"lendingType":{"id":"LNX","iso2code":"XX","value":"Not classified"},"capita'
 b'lCity":"Ottawa","longitude":"-75.6919","latitude":"45.4215"},{"id":"CEA","is'
 b'o2Code":"C4","name":"East Asia and the Pacific (IFC classification)","region'
 b'":{"id":"NA","iso2code":"NA","value":"Aggregates"},"adminregion":{"id":"","i'
 b'so2code":"","value":""},"incomeLevel":{"id":"NA","iso2code":"NA","value":"Ag'
 b'gregates"},"lendingType":{"id":"","iso2code":"","value":"Aggregates"},"capit'
 b'alCity":"","longitude":"","latitude":""},{"id":"CEB","iso2Code":"B8","name":'
 b'"Central Europe and the Baltics","region":{"id":"NA","iso2code":"NA","value"'
 b':"Aggregates"},"adminregion":{"id":"","iso2code":"","value":""},"incomeLevel'
 b'":{"id":"NA","iso2code":"NA","value":"Aggregates"},"lendingType":{"id":"","i'
 b'so2code":"","value":"Aggregates"},"capitalCity":"","longitude":"","latitude"'
 b':""},{"id":"CEU","iso2Code":"C5","name":"Europe and Central Asia (IFC classi'
 b'fication)","region":{"id":"NA","iso2code":"NA","value":"Aggregates"},"adminr'
 b'egion":{"id":"","iso2code":"","value":""},"incomeLevel":{"id":"NA","iso2code'
 b'":"NA","value":"Aggregates"},"lendingType":{"id":"","iso2code":"","value":"A'
 b'ggregates"},"capitalCity":"","longitude":"","latitude":""},{"id":"CHE","iso2'
 b'Code":"CH","name":"Switzerland","region":{"id":"ECS","iso2code":"Z7","value"'
 b':"Europe & Central Asia"},"adminregion":{"id":"","iso2code":"","value":""},"'
 b'incomeLevel":{"id":"HIC","iso2code":"XD","value":"High income"},"lendingType'
 b'":{"id":"LNX","iso2code":"XX","value":"Not classified"},"capitalCity":"Bern"'
 b',"longitude":"7.44821","latitude":"46.948"},{"id":"CHI","iso2Code":"JG","nam'
 b'e":"Channel Islands","region":{"id":"ECS","iso2code":"Z7","value":"Europe & '
 b'Central Asia"},"adminregion":{"id":"","iso2code":"","value":""},"incomeLevel'
 b'":{"id":"HIC","iso2code":"XD","value":"High income"},"lendingType":{"id":"LN'
 b'X","iso2code":"XX","value":"Not classified"},"capitalCity":"","longitude":""'
 b',"latitude":""},{"id":"CHL","iso2Code":"CL","name":"Chile","region":{"id":"L'

In [8]:
coun_json=json.loads(counT,strict=False)

In [9]:
type(coun_json)

list

In [10]:
pprint(coun_json[1])

[{'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'capitalCity': 'Oranjestad',
  'id': 'ABW',
  'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
  'iso2Code': 'AW',
  'latitude': '12.5167',
  'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
  'longitude': '-70.0167',
  'name': 'Aruba',
  'region': {'id': 'LCN',
             'iso2code': 'ZJ',
             'value': 'Latin America & Caribbean '}},
 {'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'capitalCity': '',
  'id': 'AFE',
  'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'iso2Code': 'ZH',
  'latitude': '',
  'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
  'longitude': '',
  'name': 'Africa Eastern and Southern',
  'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}},
 {'adminregion': {'id': 'SAS', 'iso2code': '8S', 'value': 'South Asia'},
  'capitalCity': 'Kabul',
  'id': 'AFG',
  'incomeLevel': {'id': 'LIC', 'iso2code': 'XM', 'value': 'Low income'},
  'iso2Code': 'AF',
  'latitude': '34.5228',
  'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'},
  'longitude': '69.1761',
  'name': 'Afghanistan',
  'region': {'id': 'SAS', 'iso2code': '8S', 'value': 'South Asia'}},
 {'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'capitalCity': '',
  'id': 'AFR',
  'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'iso2Code': 'A9',
  'latitude': '',
  'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
  'longitude': '',
  'name': 'Africa',
  'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}},
 {'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'capitalCity': '',
  'id': 'AFW',
  'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'iso2Code': 'ZI',
  'latitude': '',
  'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
  'longitude': '',
  'name': 'Africa Western and Central',
  'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}},
 {'adminregion': {'id': 'SSA',
                  'iso2code': 'ZF',
                  'value': 'Sub-Saharan Africa (excluding high income)'},
  'capitalCity': 'Luanda',
  'id': 'AGO',
  'incomeLevel': {'id': 'LMC',
                  'iso2code': 'XN',
                  'value': 'Lower middle income'},
  'iso2Code': 'AO',
  'latitude': '-8.81155',
  'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
  'longitude': '13.242',
  'name': 'Angola',
  'region': {'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-Saharan Africa '}},
 {'adminregion': {'id': 'ECA',
                  'iso2code': '7E',
                  'value': 'Europe & Central Asia (excluding high income)'},
  'capitalCity': 'Tirane',
  'id': 'ALB',
  'incomeLevel': {'id': 'UMC',
                  'iso2code': 'XT',
                  'value': 'Upper middle income'},
  'iso2Code': 'AL',
  'latitude': '41.3317',
  'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
  'longitude': '19.8172',
  'name': 'Albania',
  'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'}},
 {'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'capitalCity': 'Andorra la Vella',
  'id': 'AND',
  'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
  'iso2Code': 'AD',
  'latitude': '42.5075',
  'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
  'longitude': '1.5218',
  'name': 'Andorra',
  'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'}},
 {'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'capitalCity': '',
  'id': 'ARB',
  'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'iso2Code': '1A',
  'latitude': '',
  'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
  'longitude': '',
  'name': 'Arab World',
  'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}},
 {'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'capitalCity': 'Abu Dhabi',
  'id': 'ARE',
  'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
  'iso2Code': 'AE',
  'latitude': '24.4764',
  'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
  'longitude': '54.3705',
  'name': 'United Arab Emirates',
  'region': {'id': 'MEA',
             'iso2code': 'ZQ',
             'value': 'Middle East & North Africa'}},
 {'adminregion': {'id': 'LAC',
                  'iso2code': 'XJ',
                  'value': 'Latin America & Caribbean (excluding high income)'},
  'capitalCity': 'Buenos Aires',
  'id': 'ARG',
  'incomeLevel': {'id': 'UMC',
                  'iso2code': 'XT',
                  'value': 'Upper middle income'},
  'iso2Code': 'AR',
  'latitude': '-34.6118',
  'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
  'longitude': '-58.4173',
  'name': 'Argentina',
  'region': {'id': 'LCN',
             'iso2code': 'ZJ',
             'value': 'Latin America & Caribbean '}},
 {'adminregion': {'id': 'ECA',
                  'iso2code': '7E',
                  'value': 'Europe & Central Asia (excluding high income)'},
  'capitalCity': 'Yerevan',
  'id': 'ARM',
  'incomeLevel': {'id': 'UMC',
                  'iso2code': 'XT',
                  'value': 'Upper middle income'},
  'iso2Code': 'AM',
  'latitude': '40.1596',
  'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
  'longitude': '44.509',
  'name': 'Armenia',
  'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'}},
 {'adminregion': {'id': 'EAP',
                  'iso2code': '4E',
                  'value': 'East Asia & Pacific (excluding high income)'},
  'capitalCity': 'Pago Pago',
  'id': 'ASM',
  'incomeLevel': {'id': 'UMC',
                  'iso2code': 'XT',
                  'value': 'Upper middle income'},
  'iso2Code': 'AS',
  'latitude': '-14.2846',
  'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
  'longitude': '-170.691',
  'name': 'American Samoa',
  'region': {'id': 'EAS', 'iso2code': 'Z4', 'value': 'East Asia & Pacific'}},
 {'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'capitalCity': "Saint John's",
  'id': 'ATG',
  'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
  'iso2Code': 'AG',
  'latitude': '17.1175',
  'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
  'longitude': '-61.8456',
  'name': 'Antigua and Barbuda',
  'region': {'id': 'LCN',
             'iso2code': 'ZJ',
             'value': 'Latin America & Caribbean '}},
 {'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'capitalCity': 'Canberra',
  'id': 'AUS',
  'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
  'iso2Code': 'AU',
  'latitude': '-35.282',
  'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
  'longitude': '149.129',
  'name': 'Australia',
  'region': {'id': 'EAS', 'iso2code': 'Z4', 'value': 'East Asia & Pacific'}},
 {'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'capitalCity': 'Vienna',
  'id': 'AUT',
  'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
  'iso2Code': 'AT',
  'latitude': '48.2201',
  'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
  'longitude': '16.3798',
  'name': 'Austria',
  'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'}},
 {'adminregion': {'id': 'ECA',
                  'iso2code': '7E',
                  'value': 'Europe & Central Asia (excluding high income)'},
  'capitalCity': 'Baku',
  'id': 'AZE',
  'incomeLevel': {'id': 'UMC',
                  'iso2code': 'XT',
                  'value': 'Upper middle income'},
  'iso2Code': 'AZ',
  'latitude': '40.3834',
  'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
  'longitude': '49.8932',
  'name': 'Azerbaijan',
  'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'}},
 {'adminregion': {'id': 'SSA',
                  'iso2code': 'ZF',
                  'value': 'Sub-Saharan Africa (excluding high income)'},
  'capitalCity': 'Bujumbura',
  'id': 'BDI',
  'incomeLevel': {'id': 'LIC', 'iso2code': 'XM', 'value': 'Low income'},
  'iso2Code': 'BI',
  'latitude': '-3.3784',
  'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'},
  'longitude': '29.3639',
  'name': 'Burundi',
  'region': {'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-Saharan Africa '}},
 {'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'capitalCity': '',
  'id': 'BEA',
  'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'iso2Code': 'B4',
  'latitude': '',
  'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
  'longitude': '',
  'name': 'East Asia & Pacific (IBRD-only countries)',
  'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}},
 {'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'capitalCity': '',
  'id': 'BEC',
  'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'iso2Code': 'B7',
  'latitude': '',
  'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
  'longitude': '',
  'name': 'Europe & Central Asia (IBRD-only countries)',
  'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}},
 {'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'capitalCity': 'Brussels',
  'id': 'BEL',
  'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
  'iso2Code': 'BE',
  'latitude': '50.8371',
  'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
  'longitude': '4.36761',
  'name': 'Belgium',
  'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'}},
 {'adminregion': {'id': 'SSA',
                  'iso2code': 'ZF',
                  'value': 'Sub-Saharan Africa (excluding high income)'},
  'capitalCity': 'Porto-Novo',
  'id': 'BEN',
  'incomeLevel': {'id': 'LMC',
                  'iso2code': 'XN',
                  'value': 'Lower middle income'},
  'iso2Code': 'BJ',
  'latitude': '6.4779',
  'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'},
  'longitude': '2.6323',
  'name': 'Benin',
  'region': {'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-Saharan Africa '}},
 {'adminregion': {'id': 'SSA',
                  'iso2code': 'ZF',
                  'value': 'Sub-Saharan Africa (excluding high income)'},
  'capitalCity': 'Ouagadougou',
  'id': 'BFA',
  'incomeLevel': {'id': 'LIC', 'iso2code': 'XM', 'value': 'Low income'},
  'iso2Code': 'BF',
  'latitude': '12.3605',
  'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'},
  'longitude': '-1.53395',
  'name': 'Burkina Faso',
  'region': {'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-Saharan Africa '}},
 {'adminregion': {'id': 'SAS', 'iso2code': '8S', 'value': 'South Asia'},
  'capitalCity': 'Dhaka',
  'id': 'BGD',
  'incomeLevel': {'id': 'LMC',
                  'iso2code': 'XN',
                  'value': 'Lower middle income'},
  'iso2Code': 'BD',
  'latitude': '23.7055',
  'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'},
  'longitude': '90.4113',
  'name': 'Bangladesh',
  'region': {'id': 'SAS', 'iso2code': '8S', 'value': 'South Asia'}},
 {'adminregion': {'id': 'ECA',
                  'iso2code': '7E',
                  'value': 'Europe & Central Asia (excluding high income)'},
  'capitalCity': 'Sofia',
  'id': 'BGR',
  'incomeLevel': {'id': 'UMC',
                  'iso2code': 'XT',
                  'value': 'Upper middle income'},
  'iso2Code': 'BG',
  'latitude': '42.7105',
  'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
  'longitude': '23.3238',
  'name': 'Bulgaria',
  'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'}},
 {'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'capitalCity': '',
  'id': 'BHI',
  'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'iso2Code': 'B1',
  'latitude': '',
  'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
  'longitude': '',
  'name': 'IBRD countries classified as high income',
  'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}},
 {'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'capitalCity': 'Manama',
  'id': 'BHR',
  'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
  'iso2Code': 'BH',
  'latitude': '26.1921',
  'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
  'longitude': '50.5354',
  'name': 'Bahrain',
  'region': {'id': 'MEA',
             'iso2code': 'ZQ',
             'value': 'Middle East & North Africa'}},
 {'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'capitalCity': 'Nassau',
  'id': 'BHS',
  'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
  'iso2Code': 'BS',
  'latitude': '25.0661',
  'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
  'longitude': '-77.339',
  'name': 'Bahamas, The',
  'region': {'id': 'LCN',
             'iso2code': 'ZJ',
             'value': 'Latin America & Caribbean '}},
 {'adminregion': {'id': 'ECA',
                  'iso2code': '7E',
                  'value': 'Europe & Central Asia (excluding high income)'},
  'capitalCity': 'Sarajevo',
  'id': 'BIH',
  'incomeLevel': {'id': 'UMC',
                  'iso2code': 'XT',
                  'value': 'Upper middle income'},
  'iso2Code': 'BA',
  'latitude': '43.8607',
  'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
  'longitude': '18.4214',
  'name': 'Bosnia and Herzegovina',
  'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'}},
 {'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'capitalCity': '',
  'id': 'BLA',
  'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'iso2Code': 'B2',
  'latitude': '',
  'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
  'longitude': '',
  'name': 'Latin America & the Caribbean (IBRD-only countries)',
  'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}},
 {'adminregion': {'id': 'ECA',
                  'iso2code': '7E',
                  'value': 'Europe & Central Asia (excluding high income)'},
  'capitalCity': 'Minsk',
  'id': 'BLR',
  'incomeLevel': {'id': 'UMC',
                  'iso2code': 'XT',
                  'value': 'Upper middle income'},
  'iso2Code': 'BY',
  'latitude': '53.9678',
  'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
  'longitude': '27.5766',
  'name': 'Belarus',
  'region': {'id': 'ECS', 'iso2code': 'Z7', 'value': 'Europe & Central Asia'}},
 {'adminregion': {'id': 'LAC',
                  'iso2code': 'XJ',
                  'value': 'Latin America & Caribbean (excluding high income)'},
  'capitalCity': 'Belmopan',
  'id': 'BLZ',
  'incomeLevel': {'id': 'LMC',
                  'iso2code': 'XN',
                  'value': 'Lower middle income'},
  'iso2Code': 'BZ',
  'latitude': '17.2534',
  'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
  'longitude': '-88.7713',
  'name': 'Belize',
  'region': {'id': 'LCN',
             'iso2code': 'ZJ',
             'value': 'Latin America & Caribbean '}},
 {'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'capitalCity': '',
  'id': 'BMN',
  'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'iso2Code': 'B3',
  'latitude': '',
  'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
  'longitude': '',
  'name': 'Middle East & North Africa (IBRD-only countries)',
  'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}},
 {'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'capitalCity': 'Hamilton',
  'id': 'BMU',
  'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
  'iso2Code': 'BM',
  'latitude': '32.3293',
  'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
  'longitude': '-64.706',
  'name': 'Bermuda',
  'region': {'id': 'NAC', 'iso2code': 'XU', 'value': 'North America'}},
 {'adminregion': {'id': 'LAC',
                  'iso2code': 'XJ',
                  'value': 'Latin America & Caribbean (excluding high income)'},
  'capitalCity': 'La Paz',
  'id': 'BOL',
  'incomeLevel': {'id': 'LMC',
                  'iso2code': 'XN',
                  'value': 'Lower middle income'},
  'iso2Code': 'BO',
  'latitude': '-13.9908',
  'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
  'longitude': '-66.1936',
  'name': 'Bolivia',
  'region': {'id': 'LCN',
             'iso2code': 'ZJ',
             'value': 'Latin America & Caribbean '}},
 {'adminregion': {'id': 'LAC',
                  'iso2code': 'XJ',
                  'value': 'Latin America & Caribbean (excluding high income)'},
  'capitalCity': 'Brasilia',
  'id': 'BRA',
  'incomeLevel': {'id': 'UMC',
                  'iso2code': 'XT',
                  'value': 'Upper middle income'},
  'iso2Code': 'BR',
  'latitude': '-15.7801',
  'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
  'longitude': '-47.9292',
  'name': 'Brazil',
  'region': {'id': 'LCN',
             'iso2code': 'ZJ',
             'value': 'Latin America & Caribbean '}},
 {'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'capitalCity': 'Bridgetown',
  'id': 'BRB',
  'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
  'iso2Code': 'BB',
  'latitude': '13.0935',
  'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
  'longitude': '-59.6105',
  'name': 'Barbados',
  'region': {'id': 'LCN',
             'iso2code': 'ZJ',
             'value': 'Latin America & Caribbean '}},
 {'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'capitalCity': 'Bandar Seri Begawan',
  'id': 'BRN',
  'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'},
  'iso2Code': 'BN',
  'latitude': '4.94199',
  'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'},
  'longitude': '114.946',
  'name': 'Brunei Darussalam',
  'region': {'id': 'EAS', 'iso2code': 'Z4', 'value': 'East Asia & Pacific'}},
 {'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'capitalCity': '',
  'id': 'BSS',
  'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'iso2Code': 'B6',
  'latitude': '',
  'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
  'longitude': '',
  'name': 'Sub-Saharan Africa (IBRD-only countries)',
  'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}},
 {'adminregion': {'id': 'SAS', 'iso2code': '8S', 'value': 'South Asia'},
  'capitalCity': 'Thimphu',
  'id': 'BTN',
  'incomeLevel': {'id': 'LMC',
                  'iso2code': 'XN',
                  'value': 'Lower middle income'},
  'iso2Code': 'BT',
  'latitude': '27.5768',
  'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'},
  'longitude': '89.6177',
  'name': 'Bhutan',
  'region': {'id': 'SAS', 'iso2code': '8S', 'value': 'South Asia'}},
 {'adminregion': {'id': 'SSA',
                  'iso2code': 'ZF',
                  'value': 'Sub-Saharan Africa (excluding high income)'},
  'capitalCity': 'Gaborone',
  'id': 'BWA',
  'incomeLevel': {'id': 'UMC',
                  'iso2code': 'XT',
                  'value': 'Upper middle income'},
  'iso2Code': 'BW',
  'latitude': '-24.6544',
  'lendingType': {'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'},
  'longitude': '25.9201',
  'name': 'Botswana',
  'region': {'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-Saharan Africa '}},
 {'adminregion': {'id': '', 'iso2code': '', 'value': ''},
  'capitalCity': '',
  'id': 'CAA',
  'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'},
  'iso2Code': 'C9',
  'latitude': '',
  'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'},
  'longitude': '',
  'name': 'Sub-Saharan Africa (IFC classification)',
  'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}},
 {'adminregion': {'id': 'SSA',
                  'iso2code': 'ZF',

In [11]:
country=coun_json[1]

In [12]:
rows=[]
for y in range(len(country)):
    row={}
    #print(data1['name'])
    row['Capital']=country[y]['capitalCity']
    row['Id']=country[y]['id']
    row['IncomeId']=country[y]['incomeLevel']['id']
    row['incomeValue']=country[y]['incomeLevel']['value']
    row['IncomeISO']=country[y]['incomeLevel']['iso2code']
    row['Isco2Code']=country[y]['iso2Code']
    row['Latitude']=country[y]['latitude']
    row['LendingId']=country[y]['lendingType']['id']
    row['LendingValue']=country[y]['lendingType']['value']
    row['LendingISO']=country[y]['lendingType']['iso2code']
    row['RegionId']=country[y]['region']['id']
    row['RegionValue']=country[y]['region']['value']
    row['RegionISO']=country[y]['region']['iso2code']
    row['AdminRegionId']=country[y]['adminregion']['id']
    row['AdminRegionValue']=country[y]['adminregion']['value']
    row['AdminRegionISO']=country[y]['adminregion']['iso2code']
    row['Names']=country[y]['name']
    row['Longitude']=country[y]['longitude']
    rows.append(row)

In [13]:
counF=pd.DataFrame(rows)
counF.head()

,AdminRegionISO,AdminRegionId,AdminRegionValue,Capital,Id,IncomeISO,IncomeId,Isco2Code,Latitude,LendingISO,LendingId,LendingValue,Longitude,Names,RegionISO,RegionId,RegionValue,incomeValue
0,,,,Oranjestad,ABW,XD,HIC,AW,12.5167,XX,LNX,Not classified,-70.0167,Aruba,ZJ,LCN,Latin America & Caribbean,High income
1,,,,,AFE,NA,NA,ZH,,,,Aggregates,,Africa Eastern and Southern,NA,NA,Aggregates,Aggregates
2,8S,SAS,South Asia,Kabul,AFG,XM,LIC,AF,34.5228,XI,IDX,IDA,69.1761,Afghanistan,8S,SAS,South Asia,Low income
3,,,,,AFR,NA,NA,A9,,,,Aggregates,,Africa,NA,NA,Aggregates,Aggregates
4,,,,,AFW,NA,NA,ZI,,,,Aggregates,,Africa Western and Central,NA,NA,Aggregates,Aggregates

In [14]:
print(counF['Id'])

0     ABW
1     AFE
2     AFG
3     AFR
4     AFW
5     AGO
6     ALB
7     AND
8     ARB
9     ARE
10    ARG
11    ARM
12    ASM
13    ATG
14    AUS
15    AUT
16    AZE
17    BDI
18    BEA
19    BEC
20    BEL
21    BEN
22    BFA
23    BGD
24    BGR
25    BHI
26    BHR
27    BHS
28    BIH
29    BLA
30    BLR
31    BLZ
32    BMN
33    BMU
34    BOL
35    BRA
36    BRB
37    BRN
38    BSS
39    BTN
40    BWA
41    CAA
42    CAF
43    CAN
44    CEA
45    CEB
46    CEU
47    CHE
48    CHI
49    CHL
Name: Id, dtype: object

In [15]:
counF.to_csv('C:/Users/garim/Desktop/Project/CountryData.csv')

In [16]:
gdp1=pd.read_csv('C:/Users/garim/Desktop/Project/GDP.csv')
gdp1.tail(10)

,Series Name,Series Code,Country Name,Country Code,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
20,"GDP growth, constant (average 2010-19 prices a...",NYGDPMKTPKDZ,Burundi,BDI,..,..,..,..,1.6,1.8,0.3,2.0,2.5,3.0
21,"GDP growth, constant (average 2010-19 prices a...",NYGDPMKTPKDZ,Cabo Verde,CPV,..,..,..,..,4.5,5.7,-14.0,3.9,5.2,6.1
22,"GDP growth, constant (average 2010-19 prices a...",NYGDPMKTPKDZ,Cambodia,KHM,..,..,..,..,7.5,7.1,-3.1,4.0,5.2,6.0
23,"GDP growth, constant (average 2010-19 prices a...",NYGDPMKTPKDZ,Cameroon,CMR,..,..,..,..,4.1,3.7,-2.1,2.1,2.7,3.8
24,"GDP growth, constant (average 2010-19 prices a...",NYGDPMKTPKDZ,Central African Republic,CAF,..,..,..,..,3.7,3.1,0.0,0.7,2.8,4.4
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Data from database: Global Economic Prospects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Last Updated: 06/08/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
gdp1 = gdp1.drop(columns=["2014", "2015",'2016','2017'])

In [18]:
gdp1.head()

,Series Name,Series Code,Country Name,Country Code,2018,2019,2020,2021,2022,2023
0,"GDP growth, constant (average 2010-19 prices a...",NYGDPMKTPKDZ,Advanced Economies,AME,2.3,1.6,-4.7,5.4,4.0,2.2
1,"GDP growth, constant (average 2010-19 prices a...",NYGDPMKTPKDZ,Afghanistan,AFG,1.2,3.9,-1.9,1.0,2.6,3.0
2,"GDP growth, constant (average 2010-19 prices a...",NYGDPMKTPKDZ,Albania,ALB,4.1,2.2,-3.3,4.4,3.7,3.7
3,"GDP growth, constant (average 2010-19 prices a...",NYGDPMKTPKDZ,Algeria,DZA,1.2,0.8,-5.5,3.6,2.3,1.6
4,"GDP growth, constant (average 2010-19 prices a...",NYGDPMKTPKDZ,Angola,AGO,-2.0,-0.6,-5.2,0.5,3.3,3.5

In [19]:
gdp1.shape

(30, 10)

In [20]:
gdp2=gdp1

In [21]:
gdp1 = gdp1.drop(labels=range(25, 30), axis=0)

In [22]:
gdp1.tail(10)

,Series Name,Series Code,Country Name,Country Code,2018,2019,2020,2021,2022,2023
15,"GDP growth, constant (average 2010-19 prices a...",NYGDPMKTPKDZ,Bosnia and Herzegovina,BIH,3.7,2.8,-4.3,2.8,3.5,3.7
16,"GDP growth, constant (average 2010-19 prices a...",NYGDPMKTPKDZ,Botswana,BWA,4.5,3.0,-7.9,6.9,4.3,4.1
17,"GDP growth, constant (average 2010-19 prices a...",NYGDPMKTPKDZ,Brazil,BRA,1.8,1.4,-4.1,4.5,2.5,2.3
18,"GDP growth, constant (average 2010-19 prices a...",NYGDPMKTPKDZ,Bulgaria,BGR,3.1,3.7,-4.2,2.6,3.3,3.4
19,"GDP growth, constant (average 2010-19 prices a...",NYGDPMKTPKDZ,Burkina Faso,BFA,6.7,5.7,0.6,3.1,5.0,5.7
20,"GDP growth, constant (average 2010-19 prices a...",NYGDPMKTPKDZ,Burundi,BDI,1.6,1.8,0.3,2.0,2.5,3.0
21,"GDP growth, constant (average 2010-19 prices a...",NYGDPMKTPKDZ,Cabo Verde,CPV,4.5,5.7,-14.0,3.9,5.2,6.1
22,"GDP growth, constant (average 2010-19 prices a...",NYGDPMKTPKDZ,Cambodia,KHM,7.5,7.1,-3.1,4.0,5.2,6.0
23,"GDP growth, constant (average 2010-19 prices a...",NYGDPMKTPKDZ,Cameroon,CMR,4.1,3.7,-2.1,2.1,2.7,3.8
24,"GDP growth, constant (average 2010-19 prices a...",NYGDPMKTPKDZ,Central African Republic,CAF,3.7,3.1,0.0,0.7,2.8,4.4

In [23]:
gdp1.rename(columns={'Country Code':'Code'},inplace=True)

In [24]:
gdp1.rename(columns={'Country Name':'CName'},inplace=True)

In [25]:
type(gdp1)

pandas.core.frame.DataFrame

In [26]:
!pip install sqldf

Requirement already satisfied: sqldf in c:\users\garim\anaconda3\lib\site-packages (0.4.2)

In [27]:
import sqldf

In [28]:
CF=sqldf.run('select * from counF join gdp1 on counF.Id=gdp1.Code')
CF.head()

C:\Users\garim\Anaconda3\lib\site-packages\pandas\core\generic.py:2531: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  dtype=dtype, method=method)

,index,AdminRegionISO,AdminRegionId,AdminRegionValue,Capital,Id,IncomeISO,IncomeId,Isco2Code,Latitude,...,Series Name,Series Code,CName,Code,2018,2019,2020,2021,2022,2023
0,2,8S,SAS,South Asia,Kabul,AFG,XM,LIC,AF,34.5228,...,"GDP growth, constant (average 2010-19 prices a...",NYGDPMKTPKDZ,Afghanistan,AFG,1.2,3.9,-1.9,1.0,2.6,3.0
1,5,ZF,SSA,Sub-Saharan Africa (excluding high income),Luanda,AGO,XN,LMC,AO,-8.81155,...,"GDP growth, constant (average 2010-19 prices a...",NYGDPMKTPKDZ,Angola,AGO,-2.0,-0.6,-5.2,0.5,3.3,3.5
2,6,7E,ECA,Europe & Central Asia (excluding high income),Tirane,ALB,XT,UMC,AL,41.3317,...,"GDP growth, constant (average 2010-19 prices a...",NYGDPMKTPKDZ,Albania,ALB,4.1,2.2,-3.3,4.4,3.7,3.7
3,10,XJ,LAC,Latin America & Caribbean (excluding high income),Buenos Aires,ARG,XT,UMC,AR,-34.6118,...,"GDP growth, constant (average 2010-19 prices a...",NYGDPMKTPKDZ,Argentina,ARG,-2.6,-2.1,-9.9,6.4,1.7,1.9
4,11,7E,ECA,Europe & Central Asia (excluding high income),Yerevan,ARM,XT,UMC,AM,40.1596,...,"GDP growth, constant (average 2010-19 prices a...",NYGDPMKTPKDZ,Armenia,ARM,5.2,7.6,-7.6,3.4,4.3,5.3

In [29]:
cols=[]
count=1
for column in CF.columns:
    if column=='index':
        cols.append(f'index_{count}')
        count+=1
        continue
    cols.append(column)
CF.columns=cols

In [30]:
#List countries with income level of "Upper middle income"
UpIncome=sqldf.run('select CName as Country from CF where IncomeValue="Upper middle income"')
UpIncome.head(20)

                  Country
0                 Albania
1               Argentina
2                 Armenia
3              Azerbaijan
4                Bulgaria
5  Bosnia and Herzegovina
6                 Belarus
7                  Brazil
8                Botswana

In [31]:
#List countries with income level of "Low income" per region.
LowIncome=sqldf.run('select CName as Country, RegionValue as Region from CF where IncomeValue="Low income" order by RegionValue, CName')
LowIncome.head(20)

                    Country               Region
0               Afghanistan           South Asia
1              Burkina Faso  Sub-Saharan Africa
2                   Burundi  Sub-Saharan Africa
3  Central African Republic  Sub-Saharan Africa

In [32]:
#Calculate cumulative/running value of GDP per region ordered by income from lowest to highest and country name.
CuGDP=sqldf.run('select CName as Country,RegionValue as Region, IncomeValue, round(cast(sum(COALESCE("2018", 0) + COALESCE("2019", 0) + COALESCE("2020", 0) + COALESCE("2021", 0) + COALESCE("2022", 0) + COALESCE("2023", 0)) as numeric),2) as CummulativeGDP from CF group by RegionValue order by CummulativeGDP asc, RegionValue asc')
CuGDP.head(20)

,Country,Region,incomeValue,CummulativeGDP
0,Bahrain,Middle East & North Africa,High income,8.2
1,Argentina,Latin America & Caribbean,Upper middle income,15.7
2,Afghanistan,South Asia,Low income,59.3
3,Albania,Europe & Central Asia,Upper middle income,71.1
4,Angola,Sub-Saharan Africa,Lower middle income,100.2

In [33]:
#Calculate percentage difference in value of GDP year-on-year per country
CalGDP=sqldf.run('select CName as Country, round(CAST(100 * (("2019" - "2018")/ "2018") AS numeric), 2) AS "2018_2019",round(CAST(100 * (("2020" - "2019")/ "2019") AS numeric), 2) AS "2019_2020",round(CAST(100 * (("2021" - "2020")/ "2020") AS numeric), 2) AS "2020_2021",round(CAST(100 * (("2022" - "2021")/ "2021") AS numeric), 2) AS "2021_2022",round(CAST(100 * (("2023" - "2022")/ "2022") AS numeric), 2) AS "2022_2023" from CF')
CalGDP.head(20)

,Country,2018_2019,2019_2020,2020_2021,2021_2022,2022_2023
0,Afghanistan,225.00,-148.72,-152.63,160.00,15.38
1,Angola,-70.00,766.67,-109.62,560.00,6.06
2,Albania,-46.34,-250.00,-233.33,-15.91,0.00
3,Argentina,-19.23,371.43,-164.65,-73.44,11.76
4,Armenia,46.15,-200.00,-144.74,26.47,23.26
5,Azerbaijan,46.67,-295.45,-165.12,39.29,-12.82
6,Burundi,12.50,-83.33,566.67,25.00,20.00
7,Benin,2.99,-71.01,150.00,20.00,8.33
8,Burkina Faso,-14.93,-89.47,416.67,61.29,14.00
9,Bangladesh,3.80,-70.73,50.00,41.67,21.57
10,Bulgaria,19.35,-213.51,-161.90,26.92,3.03
11,Bahrain,-5.00,-384.21,-161.11,-3.03,0.00
12,Bosnia and Herzegovina,-24.32,-253.57,-165.12,25.00,5.71
13,Belarus,-54.84,-164.29,144.44,-186.36,-36.84
14,Belize,-37.93,-883.33,-113.48,236.84,-34.38
15,Bolivia,-47.62,-500.00,-153.41,-25.53,-14.29
16,Brazil,-22.22,-392.86,-209.76,-44.44,-8.00
17,Bhutan,13.16,-118.60,125.00,-377.78,12.00
18,Botswana,-33.33,-363.33,-187.34,-37.68,-4.65
19,Central African Republic,-16.22,-100.00,NaN,300.00,57.14

In [34]:
Demo=sqldf.run('select *, (COALESCE("2018", 0) + COALESCE("2019", 0) + COALESCE("2020", 0) + COALESCE("2021", 0) + COALESCE("2022", 0) + COALESCE("2023", 0)) as Total from CF')

In [35]:
cols=[]
count=10
for column in Demo.columns:
    if column=='index':
        cols.append(f'index_{count}')
        count+=1
        continue
    cols.append(column)
Demo.columns=cols

In [36]:
#List 3 countries with lowest GDP per region
Demo1=sqldf.run('select *, ROW_NUMBER() OVER (PARTITION BY RegionValue ORDER BY Total ASC) as DemG from Demo')
LowGDP= sqldf.run('SELECT RegionValue as Region, CName as Country, ROUND(CAST(Total as numeric), 2) as GDPCumm from Demo1 where DemG <= 3 order by RegionValue, DemG')
LowGDP.head(20)

                        Region                   Country  GDPCumm
0        Europe & Central Asia                   Belarus      4.5
1        Europe & Central Asia                Azerbaijan      9.5
2        Europe & Central Asia                  Bulgaria     11.9
3   Latin America & Caribbean                  Argentina     -4.6
4   Latin America & Caribbean                     Belize      3.1
5   Latin America & Caribbean                     Brazil      8.4
6   Middle East & North Africa                   Bahrain      8.2
7                   South Asia               Afghanistan      9.8
8                   South Asia                    Bhutan     16.1
9                   South Asia                Bangladesh     33.4
10         Sub-Saharan Africa                     Angola     -0.5
11         Sub-Saharan Africa                    Burundi     11.2
12         Sub-Saharan Africa   Central African Republic     14.7